[2024-03-05T16:06:51.738-0300] {processor.py:161} INFO - Started process (PID=88610) to work on /home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/example_dags/example_branch_operator_decorator.py
[2024-03-05T16:06:51.739-0300] {processor.py:830} INFO - Processing file /home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/example_dags/example_branch_operator_decorator.py for tasks to queue
[2024-03-05T16:06:51.739-0300] {logging_mixin.py:188} INFO - [2024-03-05T16:06:51.739-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/example_dags/example_branch_operator_decorator.py
[2024-03-05T16:06:51.825-0300] {logging_mixin.py:188} INFO - [2024-03-05T16:06:51.823-0300] {dagbag.py:350} ERROR - Failed to import: /home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/example_dags/example_branch_operator_decorator.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/example_dags/example_branch_operator_decorator.py", line 125, in <module>
    random_choice_venv = branching_virtualenv(choices=options)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 366, in __call__
    op = self.operator_class(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 233, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 591, in __init__
    raise AirflowException("PythonVirtualenvOperator requires virtualenv, please install it.")
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2024-03-05T16:06:51.825-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/example_dags/example_branch_operator_decorator.py
[2024-03-05T16:06:51.845-0300] {processor.py:183} INFO - Processing /home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/example_dags/example_branch_operator_decorator.py took 0.109 seconds
