[2024-03-06T10:58:55.762-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T10:58:55.767-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T10:58:55.767-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T10:58:55.781-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-02 00:00:00+00:00
[2024-03-06T10:58:55.784-0300] {standard_task_runner.py:60} INFO - Started process 18819 to run task
[2024-03-06T10:58:55.786-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp5i451eko']
[2024-03-06T10:58:55.788-0300] {standard_task_runner.py:88} INFO - Job 11: Subtask GOOG
[2024-03-06T10:58:55.821-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T10:58:55.869-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T10:58:56.553-0300] {history.py:222} ERROR - GOOG: No price data found, symbol may be delisted (1h 2024-01-01 -> 2024-01-02)
[2024-03-06T10:58:56.555-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T10:58:56.561-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240102T000000, start_date=20240306T135855, end_date=20240306T135856
[2024-03-06T10:58:56.603-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T10:58:56.615-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:04:08.434-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:04:08.497-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:04:08.499-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:04:08.541-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-02 00:00:00+00:00
[2024-03-06T12:04:08.580-0300] {standard_task_runner.py:60} INFO - Started process 39021 to run task
[2024-03-06T12:04:08.592-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpi9t4sl09']
[2024-03-06T12:04:08.683-0300] {standard_task_runner.py:88} INFO - Job 5: Subtask GOOG
[2024-03-06T12:04:09.168-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:04:09.926-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T12:04:11.238-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:04:11.738-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240102T000000, start_date=20240306T150408, end_date=20240306T150411
[2024-03-06T12:04:15.318-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task GOOG (index 0 is out of bounds for axis 0 with size 0; 39021)
[2024-03-06T12:04:15.368-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:04:15.481-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:15:34.733-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:15:34.768-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:15:34.769-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:15:34.845-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-02 00:00:00+00:00
[2024-03-06T12:15:34.864-0300] {standard_task_runner.py:60} INFO - Started process 46559 to run task
[2024-03-06T12:15:34.885-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpt6m_y5lh']
[2024-03-06T12:15:34.889-0300] {standard_task_runner.py:88} INFO - Job 154: Subtask GOOG
[2024-03-06T12:15:35.145-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:15:35.456-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T12:15:38.622-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:15:40.982-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240102T000000, start_date=20240306T151534, end_date=20240306T151540
[2024-03-06T12:15:41.231-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 154 for task GOOG (index 0 is out of bounds for axis 0 with size 0; 46559)
[2024-03-06T12:15:41.320-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:15:41.384-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:16:58.828-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:16:58.840-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T12:16:58.840-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:16:58.853-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-02 00:00:00+00:00
[2024-03-06T12:16:58.857-0300] {standard_task_runner.py:60} INFO - Started process 48609 to run task
[2024-03-06T12:16:58.859-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpdsbp3f9r']
[2024-03-06T12:16:58.860-0300] {standard_task_runner.py:88} INFO - Job 204: Subtask GOOG
[2024-03-06T12:16:58.922-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:16:59.016-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T12:16:59.857-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:16:59.882-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240102T000000, start_date=20240306T151658, end_date=20240306T151659
[2024-03-06T12:16:59.902-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 204 for task GOOG (index 0 is out of bounds for axis 0 with size 0; 48609)
[2024-03-06T12:16:59.919-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:16:59.940-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T14:38:34.280-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:38:34.293-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:38:34.294-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T14:38:34.311-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-02 00:00:00+00:00
[2024-03-06T14:38:34.315-0300] {standard_task_runner.py:60} INFO - Started process 82603 to run task
[2024-03-06T14:38:34.318-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmprcy2w83q']
[2024-03-06T14:38:34.320-0300] {standard_task_runner.py:88} INFO - Job 253: Subtask GOOG
[2024-03-06T14:38:34.382-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T14:38:34.474-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T14:38:35.242-0300] {history.py:222} ERROR - GOOG: No price data found, symbol may be delisted (1h 2024-01-01 -> 2024-01-02)
[2024-03-06T14:38:35.245-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T14:38:35.260-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240102T000000, start_date=20240306T173834, end_date=20240306T173835
[2024-03-06T14:38:35.297-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T14:38:35.318-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T14:48:58.451-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:48:58.463-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:48:58.464-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T14:48:58.478-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-02 00:00:00+00:00
[2024-03-06T14:48:58.483-0300] {standard_task_runner.py:60} INFO - Started process 86464 to run task
[2024-03-06T14:48:58.485-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp3_u3dclh']
[2024-03-06T14:48:58.487-0300] {standard_task_runner.py:88} INFO - Job 282: Subtask GOOG
[2024-03-06T14:48:58.551-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T14:48:58.649-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T14:48:59.165-0300] {history.py:222} ERROR - GOOG: No price data found, symbol may be delisted (1h 2024-01-01 -> 2024-01-02)
[2024-03-06T14:48:59.168-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T14:48:59.184-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240102T000000, start_date=20240306T174858, end_date=20240306T174859
[2024-03-06T14:48:59.222-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T14:48:59.243-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T14:59:51.750-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:59:51.763-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-03-06T14:59:51.764-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T14:59:51.779-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): GOOG> on 2024-01-02 00:00:00+00:00
[2024-03-06T14:59:51.783-0300] {standard_task_runner.py:60} INFO - Started process 90684 to run task
[2024-03-06T14:59:51.785-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'GOOG', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp7q73rqyc']
[2024-03-06T14:59:51.786-0300] {standard_task_runner.py:88} INFO - Job 313: Subtask GOOG
[2024-03-06T14:59:51.850-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.GOOG scheduled__2024-01-02T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T14:59:51.948-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='GOOG' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-03-06T14:59:52.444-0300] {history.py:222} ERROR - GOOG: No price data found, symbol may be delisted (1h 2024-01-01 -> 2024-01-02)
[2024-03-06T15:00:02.452-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T15:00:02.477-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=GOOG, execution_date=20240102T000000, start_date=20240306T175951, end_date=20240306T180002
[2024-03-06T15:00:02.533-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T15:00:02.556-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
